import { AuthCard, UserProfile, UserRole, EntityType } from "@/types";

// ─── Auth Cards ─────────────────────────────────────────────────────

export const authCards: AuthCard[] = [
  // Employee profiles (5)
  {
    id: "emp-management",
    title: "Management",
    subtitle: "Leadership dashboard",
    role: "employee-management",
    entityType: "employee",
    icon: "briefcase",
    color: "#00a050",
    emailSlug: "management",
  },
  {
    id: "emp-reception",
    title: "Reception",
    subtitle: "Visitor reception desk",
    role: "employee-reception",
    entityType: "employee",
    icon: "bell",
    color: "#10a050",
    emailSlug: "reception",
  },
  {
    id: "emp-hr",
    title: "Human Resources",
    subtitle: "HR management portal",
    role: "employee-hr",
    entityType: "employee",
    icon: "users",
    color: "#009050",
    emailSlug: "hr",
  },
  {
    id: "emp-it",
    title: "IT Support",
    subtitle: "IT infrastructure control",
    role: "employee-it",
    entityType: "employee",
    icon: "monitor",
    color: "#006030",
    emailSlug: "it",
  },
  {
    id: "emp-security",
    title: "Security",
    subtitle: "Security operations center",
    role: "employee-security",
    entityType: "employee",
    icon: "shield",
    color: "#008040",
    emailSlug: "security",
  },

  // Intern profiles (8)
  {
    id: "intern-mechanical",
    title: "Mechanical Engineering",
    subtitle: "Engineering department",
    role: "intern-mechanical",
    entityType: "intern",
    icon: "wrench",
    color: "#3b82f6",
    emailSlug: "mechanical",
  },
  {
    id: "intern-chemical",
    title: "Chemical Engineering",
    subtitle: "Process engineering",
    role: "intern-chemical",
    entityType: "intern",
    icon: "flask",
    color: "#6366f1",
    emailSlug: "chemical",
  },
  {
    id: "intern-electrical",
    title: "Electrical Engineering",
    subtitle: "Power & automation",
    role: "intern-electrical",
    entityType: "intern",
    icon: "zap",
    color: "#8b5cf6",
    emailSlug: "electrical",
  },
  {
    id: "intern-civil",
    title: "Civil Engineering",
    subtitle: "Infrastructure & construction",
    role: "intern-civil",
    entityType: "intern",
    icon: "building",
    color: "#a855f7",
    emailSlug: "civil",
  },
  {
    id: "intern-industrial",
    title: "Industrial Engineering",
    subtitle: "Operations optimization",
    role: "intern-industrial",
    entityType: "intern",
    icon: "cog",
    color: "#d946ef",
    emailSlug: "industrial",
  },
  {
    id: "intern-hse",
    title: "HSE",
    subtitle: "Health, Safety & Environment",
    role: "intern-hse",
    entityType: "intern",
    icon: "hard-hat",
    color: "#ec4899",
    emailSlug: "hse",
  },
  {
    id: "intern-environmental",
    title: "Environmental Science",
    subtitle: "Sustainability & compliance",
    role: "intern-environmental",
    entityType: "intern",
    icon: "leaf",
    color: "#14b8a6",
    emailSlug: "environmental",
  },
  {
    id: "intern-computer-science",
    title: "IT & Digitalization",
    subtitle: "IT & digital systems",
    role: "intern-computer-science",
    entityType: "intern",
    icon: "code",
    color: "#06b6d4",
    emailSlug: "computer",
  },

  // Visitor profiles (6)
  {
    id: "visitor-client",
    title: "Client",
    subtitle: "Client visit access",
    role: "visitor-client",
    entityType: "visitor",
    icon: "user",
    color: "#f59e0b",
    emailSlug: "client",
  },
  {
    id: "visitor-delivery",
    title: "Delivery",
    subtitle: "Delivery personnel access",
    role: "visitor-delivery",
    entityType: "visitor",
    icon: "truck",
    color: "#f97316",
    emailSlug: "delivery",
  },
  {
    id: "visitor-partner",
    title: "Partner",
    subtitle: "Partner organization access",
    role: "visitor-partner",
    entityType: "visitor",
    icon: "handshake",
    color: "#ef4444",
    emailSlug: "partner",
  },
  {
    id: "visitor-supplier",
    title: "Supplier",
    subtitle: "Supplier access portal",
    role: "visitor-supplier",
    entityType: "visitor",
    icon: "package",
    color: "#dc2626",
    emailSlug: "supplier",
  },
  {
    id: "visitor-collaborator",
    title: "Collaborator",
    subtitle: "Collaboration access",
    role: "visitor-collaborator",
    entityType: "visitor",
    icon: "users",
    color: "#b91c1c",
    emailSlug: "collaborator",
  },
  {
    id: "visitor-contractor",
    title: "Contractor",
    subtitle: "Contractor site access",
    role: "visitor-contractor",
    entityType: "visitor",
    icon: "hard-hat",
    color: "#991b1b",
    emailSlug: "contractor",
  },
];

// ─── Mock Users ─────────────────────────────────────────────────────

export const mockUsers: UserProfile[] = [
  // Employee profiles (5)
  {
    id: "1",
    name: "Ahmed Benali",
    role: "employee-management",
    entityType: "employee",
    department: "Management",
    email: "a.benali@ocp.ma",
    phone: "+212 5XX XXX XXX",
    badge: "EMP-001",
    status: "active",
  },
  {
    id: "2",
    name: "Sara Tazi",
    role: "employee-reception",
    entityType: "employee",
    department: "Reception",
    email: "s.tazi@ocp.ma",
    phone: "+212 5XX XXX XXX",
    badge: "EMP-002",
    status: "active",
  },
  {
    id: "3",
    name: "Mohammed Alaoui",
    role: "employee-hr",
    entityType: "employee",
    department: "Human Resources",
    email: "m.alaoui@ocp.ma",
    phone: "+212 5XX XXX XXX",
    badge: "EMP-003",
    status: "active",
  },
  {
    id: "4",
    name: "Karim Idrissi",
    role: "employee-it",
    entityType: "employee",
    department: "IT Department",
    email: "k.idrissi@ocp.ma",
    phone: "+212 5XX XXX XXX",
    badge: "EMP-004",
    status: "active",
  },
  {
    id: "5",
    name: "Fatima Zahra",
    role: "employee-security",
    entityType: "employee",
    department: "Security",
    email: "f.zahra@ocp.ma",
    phone: "+212 5XX XXX XXX",
    badge: "EMP-005",
    status: "active",
  },

  // Intern profiles (8)
  {
    id: "10",
    name: "Youssef Amrani",
    role: "intern-mechanical",
    entityType: "intern",
    department: "Mechanical Engineering",
    email: "y.amrani@ocp.ma",
    phone: "+212 6XX XXX XXX",
    badge: "INT-001",
    status: "active",
  },
  {
    id: "11",
    name: "Amina Bouchama",
    role: "intern-chemical",
    entityType: "intern",
    department: "Chemical Engineering",
    email: "a.bouchama@ocp.ma",
    phone: "+212 6XX XXX XXX",
    badge: "INT-002",
    status: "active",
  },
  {
    id: "12",
    name: "Omar Benjelloun",
    role: "intern-electrical",
    entityType: "intern",
    department: "Electrical Engineering",
    email: "o.benjelloun@ocp.ma",
    phone: "+212 6XX XXX XXX",
    badge: "INT-003",
    status: "active",
  },
  {
    id: "13",
    name: "Fatima Zahra Ouazzani",
    role: "intern-civil",
    entityType: "intern",
    department: "Civil Engineering",
    email: "fz.ouazzani@ocp.ma",
    phone: "+212 6XX XXX XXX",
    badge: "INT-004",
    status: "active",
  },
  {
    id: "14",
    name: "Hamza Tazi",
    role: "intern-industrial",
    entityType: "intern",
    department: "Industrial Engineering",
    email: "h.tazi@ocp.ma",
    phone: "+212 6XX XXX XXX",
    badge: "INT-005",
    status: "active",
  },
  {
    id: "15",
    name: "Nadia Idrissi",
    role: "intern-hse",
    entityType: "intern",
    department: "Health, Safety & Environment",
    email: "n.idrissi@ocp.ma",
    phone: "+212 6XX XXX XXX",
    badge: "INT-006",
    status: "active",
  },
  {
    id: "16",
    name: "Rachid Alaoui",
    role: "intern-environmental",
    entityType: "intern",
    department: "Environmental Science",
    email: "r.alaoui@ocp.ma",
    phone: "+212 6XX XXX XXX",
    badge: "INT-007",
    status: "active",
  },
  {
    id: "17",
    name: "Salma Benali",
    role: "intern-computer-science",
    entityType: "intern",
    department: "Computer Science",
    email: "s.benali@ocp.ma",
    phone: "+212 6XX XXX XXX",
    badge: "INT-008",
    status: "active",
  },

  // Visitor profiles (6)
  {
    id: "20",
    name: "Claire Dupont",
    role: "visitor-client",
    entityType: "visitor",
    department: "Phosphate Solutions Ltd",
    email: "c.dupont@psl.com",
    phone: "+33 1 XX XX XX XX",
    badge: "VIS-001",
    status: "pending",
  },
  {
    id: "21",
    name: "Jean Martin",
    role: "visitor-delivery",
    entityType: "visitor",
    department: "TransLogistics",
    email: "j.martin@translog.fr",
    phone: "+33 6 XX XX XX XX",
    badge: "VIS-002",
    status: "active",
  },
  {
    id: "22",
    name: "Maria Santos",
    role: "visitor-partner",
    entityType: "visitor",
    department: "ChemPartner Inc",
    email: "m.santos@chempartner.com",
    phone: "+351 9XX XXX XXX",
    badge: "VIS-003",
    status: "active",
  },
  {
    id: "23",
    name: "Hassan Ouazzani",
    role: "visitor-supplier",
    entityType: "visitor",
    department: "SupplyTech",
    email: "h.ouazzani@supplytech.ma",
    phone: "+212 5XX XXX XXX",
    badge: "VIS-004",
    status: "pending",
  },
  {
    id: "24",
    name: "Pierre Laurent",
    role: "visitor-collaborator",
    entityType: "visitor",
    department: "EuroChem Solutions",
    email: "p.laurent@eurochem.com",
    phone: "+33 4 XX XX XX XX",
    badge: "VIS-005",
    status: "active",
  },
  {
    id: "25",
    name: "Ahmed Kabbaj",
    role: "visitor-contractor",
    entityType: "visitor",
    department: "MorPhos Construction",
    email: "a.kabbaj@morphos.ma",
    phone: "+212 6XX XXX XXX",
    badge: "VIS-006",
    status: "active",
  },
];

// ─── Role Labels ────────────────────────────────────────────────────

export const roleLabels: Record<UserRole, string> = {
  // Employee
  "employee-management": "Employee - Management",
  "employee-reception": "Employee - Reception",
  "employee-hr": "Employee - HR",
  "employee-it": "Employee - IT Support",
  "employee-security": "Employee - Security",
  // Intern
  "intern-mechanical": "Intern - Mechanical Engineering",
  "intern-chemical": "Intern - Chemical Engineering",
  "intern-electrical": "Intern - Electrical Engineering",
  "intern-civil": "Intern - Civil Engineering",
  "intern-industrial": "Intern - Industrial Engineering",
  "intern-hse": "Intern - HSE",
  "intern-environmental": "Intern - Environmental Science",
  "intern-computer-science": "Intern - IT & Digitalization",
  // Visitor
  "visitor-client": "Visitor - Client",
  "visitor-delivery": "Visitor - Delivery",
  "visitor-partner": "Visitor - Partner",
  "visitor-supplier": "Visitor - Supplier",
  "visitor-collaborator": "Visitor - Collaborator",
  "visitor-contractor": "Visitor - Contractor",
};

export const entityLabels: Record<EntityType, string> = {
  employee: "Employee",
  intern: "Intern",
  visitor: "Visitor",
};

export const dashboardStats = {
  employee: {
    totalVisitors: 1247,
    activeOnSite: 89,
    pendingApprovals: 23,
    todayCheckIns: 156,
  },
  intern: {
    totalInterns: 45,
    activeInterns: 32,
    upcomingReviews: 8,
    completedTasks: 124,
  },
  visitor: {
    upcomingVisits: 12,
    pendingBadges: 3,
    siteRules: "View",
    visitHistory: 28,
  },
};
